apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver
  namespace: vshop
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: sqlserver
  serviceName: sqlserver
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vshop
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: sqlserver
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: sqlserver
        image: sqlserver-with-data:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 1433
          name: tcpsql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_ENABLE_HADR
          value: "1"
        - name: MSSQL_AGENT_ENABLED
          value: "1"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: sqlserver-persistent-storage
          mountPath: /var/opt/mssql
  volumeClaimTemplates:
  - metadata:
      name: sqlserver-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
