# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY VShop.ProductApi.csproj ./
RUN dotnet restore

# copy everything else and build app
COPY . .
RUN dotnet publish VShop.ProductApi.csproj -c release -o /app 

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "VShop.ProductApi.dll"]