apiVersion: v1
kind: Service
metadata:
  name: vshop-product-api
  namespace: vshop
spec:
  selector:
    app.kubernetes.io/instance: vshop-product-api
  ports:
    - name: http      
      port: 8080
      targetPort: 8080

