apiVersion: v1
kind: Service
metadata:
  name: vshop-web-ui
  namespace: vshop
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: vshop-web-ui
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32001
